services:
  database:
    hostname: postgres-database
    image: postgres
    container_name: bookstore-dev-database
    #    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - database-shared:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  server:
    build: .
    image: bookstore-dev-server
    container_name: bookstore-dev-server
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_SECURITY_JWT_SECRET=secret
      - SPRING_SECURITY_JWT_EXPIRATION_ACCESS=1800000
      - SPRING_SECURITY_JWT_EXPIRATION_REFRESH=604800000
      - SPRING_SECURITY_CORS_ALLOWED_ORIGINS=*

volumes:
  database-shared:
    name: bookstore-postgres-volume